language: node_js
node_js:
  - "0.8"

install:
  - npm install
  - ./node_modules/.bin/bower install

before_script:
  - "npm start &" # start a Web server
  - sleep 3       # give Web server some time to bind to sockets, etc
